// src/app/layout.tsx

import type { Metadata } from "next";
// Correct way to import Geist fonts from the 'geist' package
import { GeistSans } from 'geist/font/sans'; // Import from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'; // Import from 'geist/font/mono'
import "./globals.css";

// Assign GeistSans and GeistMono directly. They are already the font objects.
// DO NOT call them as functions with {}
const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}